services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Pixelant\Interest\:
    resource: '../Classes/*'

  Pixelant\Interest\DataHandling\Operation\Event\Handler\InsertTranslationFields:
    tags:
      - name: event.listener
        identifier: insertTranslationFields
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: resolveStoragePid

  Pixelant\Interest\DataHandling\Operation\Event\Handler\ResolveStoragePid:
    tags:
      - name: event.listener
        identifier: resolveStoragePid
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: generateRecordOperationHash

  Pixelant\Interest\DataHandling\Operation\Event\Handler\GenerateRecordOperationHash:
    tags:
      - name: event.listener
        identifier: generateRecordOperationHash
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: stopIfRepeatingPreviousRecord

  Pixelant\Interest\DataHandling\Operation\Event\Handler\StopIfRepeatingPreviousRecordOperation:
    tags:
      - name: event.listener
        identifier: stopIfRepeatingPreviousRecord
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: persistFileData

  Pixelant\Interest\DataHandling\Operation\Event\Handler\PersistFileData:
    tags:
      - name: event.listener
        identifier: persistFileData
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: deferSysFileReferenceRecordOperation

  Pixelant\Interest\DataHandling\Operation\Event\Handler\DeferSysFileReference:
    tags:
      - name: event.listener
        identifier: deferSysFileReferenceRecordOperation
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: relationSortingAsMetaData

  Pixelant\Interest\DataHandling\Operation\Event\Handler\RelationSortingAsMetaData:
    tags:
      - name: event.listener
        identifier: relationSortingAsMetaData
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: validateFieldNames

  Pixelant\Interest\DataHandling\Operation\Event\Handler\ValidateFieldNames:
    tags:
      - name: event.listener
        identifier: validateFieldNames
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: setContentObjectRendererLanguage

  Pixelant\Interest\DataHandling\Operation\Event\Handler\SetContentObjectRendererLanguage:
    tags:
      - name: event.listener
        identifier: setContentObjectRendererLanguage
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: applyFieldDataTransformations

  Pixelant\Interest\DataHandling\Operation\Event\Handler\ApplyFieldDataTransformations:
    tags:
      - name: event.listener
        identifier: applyFieldDataTransformations
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: sanitizeFieldValues

  Pixelant\Interest\DataHandling\Operation\Event\Handler\SanitizeFieldValues:
    tags:
      - name: event.listener
        identifier: sanitizeFieldValues
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: deferMissingPidRemoteId

  Pixelant\Interest\DataHandling\Operation\Event\Handler\DeferMissingPidRemoteId:
    tags:
      - name: event.listener
        identifier: deferMissingPidRemoteId
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: filterPendingRelations

  Pixelant\Interest\DataHandling\Operation\Event\Handler\FilterPendingRelations:
    tags:
      - name: event.listener
        identifier: filterPendingRelations
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: prepareRelations

  Pixelant\Interest\DataHandling\Operation\Event\Handler\PrepareRelations:
    tags:
      - name: event.listener
        identifier: prepareRelations
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: removeFieldsWithNullValue

  Pixelant\Interest\DataHandling\Operation\Event\Handler\RemoveFieldsWithNullValue:
    tags:
      - name: event.listener
        identifier: removeFieldsWithNullValue
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: setPid

  Pixelant\Interest\DataHandling\Operation\Event\Handler\SetPid:
    tags:
      - name: event.listener
        identifier: setPid
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        after: removeFieldsWithNullValue

  Pixelant\Interest\DataHandling\Operation\Event\Handler\DetectUpdatedForeignFieldValues:
    tags:
      - name: event.listener
        identifier: detectUpdatedForeignFieldValues
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationInvocationEvent
        before: convertArrayValuesToScalar

  Pixelant\Interest\DataHandling\Operation\Event\Handler\ConvertArrayValuesToScalar:
    tags:
      - name: event.listener
        identifier: convertArrayValuesToScalar
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationInvocationEvent
        before: resolvePendingRelations

  Pixelant\Interest\DataHandling\Operation\Event\Handler\ResolvePendingRelations:
    tags:
      - name: event.listener
        identifier: resolvePendingRelations
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationInvocationEvent
        before: processDatamap

  Pixelant\Interest\DataHandling\Operation\Event\Handler\ProcessDatamap:
    tags:
      - name: event.listener
        identifier: processDatamap
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationInvocationEvent
        before: processUpdatedForeignFieldValues

  Pixelant\Interest\DataHandling\Operation\Event\Handler\ProcessUpdatedForeignFieldValues:
    tags:
      - name: event.listener
        identifier: processUpdatedForeignFieldValues
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationInvocationEvent
        before: processCmdmap

  Pixelant\Interest\DataHandling\Operation\Event\Handler\ProcessCmdmap:
    tags:
      - name: event.listener
        identifier: processCmdmap
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationInvocationEvent
        before: setUid

  Pixelant\Interest\DataHandling\Operation\Event\Handler\SetUid:
    tags:
      - name: event.listener
        identifier: setUid
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationInvocationEvent
        before: mapRemoteId

  Pixelant\Interest\DataHandling\Operation\Event\Handler\MapRemoteId:
    tags:
      - name: event.listener
        identifier: mapRemoteId
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationInvocationEvent
        before: persistPendingRelationInformation

  Pixelant\Interest\DataHandling\Operation\Event\Handler\PersistPendingRelationInformation:
    tags:
      - name: event.listener
        identifier: persistPendingRelationInformation
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationInvocationEvent
        before: processDeferredRecordOperations

  Pixelant\Interest\DataHandling\Operation\Event\Handler\ProcessDeferredRecordOperations:
    tags:
      - name: event.listener
        identifier: processDeferredRecordOperations
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationInvocationEvent
        before: updateCountOnForeignSideOfInlineRecord

  Pixelant\Interest\DataHandling\Operation\Event\Handler\UpdateCountOnForeignSideOfInlineRecord:
    tags:
      - name: event.listener
        identifier: updateCountOnForeignSideOfInlineRecord
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationInvocationEvent
        before: cleanUpPendingRelations

  Pixelant\Interest\DataHandling\Operation\Event\Handler\ForeignRelationSorting:
    tags:
      - name: event.listener
        identifier: foreignRelationSorting
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationInvocationEvent
        before: cleanUpPendingRelations

  Pixelant\Interest\DataHandling\Operation\Event\Handler\RemovePendingRelationsForCreatedRecord:
    tags:
      - name: event.listener
        identifier: removePendingRelationsForCreatedRecord
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationInvocationEvent
        after: foreignRelationSorting

  Pixelant\Interest\DataHandling\Operation\Event\Handler\RemovePendingRelationsForDeletedRecord:
    tags:
      - name: event.listener
        identifier: removePendingRelationsForDeletedRecord
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationInvocationEvent
        after: foreignRelationSorting

  Pixelant\Interest\EventHandler\DeleteRemoteIdForDeletedFile:
    tags:
      - name: event.listener
        identifier: deleteRemoteIdForDeletedFile
        event: TYPO3\CMS\Core\Resource\Event\AfterFileDeletedEvent

  Pixelant\Interest\Command\CreateCommandController:
    tags:
      - name: console.command
        command: 'interest:create'
        schedulable: false

  Pixelant\Interest\Command\DeleteCommandController:
    tags:
      - name: console.command
        command: 'interest:delete'
        schedulable: false

  Pixelant\Interest\Command\UpdateCommandController:
    tags:
      - name: console.command
        command: 'interest:update'
        schedulable: false

  Pixelant\Interest\Command\ReadCommandController:
    tags:
      - name: console.command
        command: 'interest:read'
        schedulable: false

  Pixelant\Interest\Command\PendingRelationsCommandController:
    tags:
      - name: console.command
        command: 'interest:pendingrelations'
        schedulable: false

  Pixelant\Interest\Command\ClearRecordHashCommandController:
    tags:
      - name: console.command
        command: 'interest:clearhash'
        schedulable: false
