services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  FriendsOfTYPO3\Interest\:
    resource: '../Classes/*'

  FriendsOfTYPO3\Interest\DataHandling\Operation\Event\Handler\InsertTranslationFields:
    tags:
      - name: event.listener
        identifier: insertTranslationFields
        event: FriendsOfTYPO3\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: resolveStoragePid

  FriendsOfTYPO3\Interest\DataHandling\Operation\Event\Handler\ResolveStoragePid:
    tags:
      - name: event.listener
        identifier: resolveStoragePid
        event: FriendsOfTYPO3\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: generateRecordOperationHash

  FriendsOfTYPO3\Interest\DataHandling\Operation\Event\Handler\GenerateRecordOperationHash:
    tags:
      - name: event.listener
        identifier: generateRecordOperationHash
        event: FriendsOfTYPO3\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: stopIfRepeatingPreviousRecord

  FriendsOfTYPO3\Interest\DataHandling\Operation\Event\Handler\StopIfRepeatingPreviousRecordOperation:
    tags:
      - name: event.listener
        identifier: stopIfRepeatingPreviousRecord
        event: FriendsOfTYPO3\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: persistFileData

  FriendsOfTYPO3\Interest\DataHandling\Operation\Event\Handler\PersistFileData:
    tags:
      - name: event.listener
        identifier: persistFileData
        event: FriendsOfTYPO3\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: deferSysFileReferenceRecordOperation

  FriendsOfTYPO3\Interest\DataHandling\Operation\Event\Handler\DeferSysFileReference:
    tags:
      - name: event.listener
        identifier: deferSysFileReferenceRecordOperation
        event: FriendsOfTYPO3\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: relationSortingAsMetaData

  FriendsOfTYPO3\Interest\DataHandling\Operation\Event\Handler\RelationSortingAsMetaData:
    tags:
      - name: event.listener
        identifier: relationSortingAsMetaData
        event: FriendsOfTYPO3\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: validateFieldNames

  FriendsOfTYPO3\Interest\DataHandling\Operation\Event\Handler\ValidateFieldNames:
    tags:
      - name: event.listener
        identifier: validateFieldNames
        event: FriendsOfTYPO3\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: setContentObjectRendererLanguage

  FriendsOfTYPO3\Interest\DataHandling\Operation\Event\Handler\SetContentObjectRendererLanguage:
    tags:
      - name: event.listener
        identifier: setContentObjectRendererLanguage
        event: FriendsOfTYPO3\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: applyFieldDataTransformations

  FriendsOfTYPO3\Interest\DataHandling\Operation\Event\Handler\ApplyFieldDataTransformations:
    tags:
      - name: event.listener
        identifier: applyFieldDataTransformations
        event: FriendsOfTYPO3\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: sanitizeFieldValues

  FriendsOfTYPO3\Interest\DataHandling\Operation\Event\Handler\SanitizeFieldValues:
    tags:
      - name: event.listener
        identifier: sanitizeFieldValues
        event: FriendsOfTYPO3\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: deferIfPidDoesNotYetExist

  FriendsOfTYPO3\Interest\DataHandling\Operation\Event\Handler\DeferIfPidDoesNotYetExist:
    tags:
      - name: event.listener
        identifier: deferIfPidDoesNotYetExist
        event: FriendsOfTYPO3\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: mapUidsAndExtractPendingRelations

  FriendsOfTYPO3\Interest\DataHandling\Operation\Event\Handler\MapUidsAndExtractPendingRelations:
    tags:
      - name: event.listener
        identifier: mapUidsAndExtractPendingRelations
        event: FriendsOfTYPO3\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: removeFieldsWithNullValue

  FriendsOfTYPO3\Interest\DataHandling\Operation\Event\Handler\RemoveFieldsWithNullValue:
    tags:
      - name: event.listener
        identifier: removeFieldsWithNullValue
        event: FriendsOfTYPO3\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: removeEmptyValuesFromRelationFieldArrays

  FriendsOfTYPO3\Interest\DataHandling\Operation\Event\Handler\RemoveEmptyValuesFromRelationFieldArrays:
    tags:
      - name: event.listener
        identifier: removeEmptyValuesFromRelationFieldArrays
        event: FriendsOfTYPO3\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: convertRelationFieldArraysToCsv

  FriendsOfTYPO3\Interest\DataHandling\Operation\Event\Handler\ConvertRelationFieldArraysToCsv:
    tags:
      - name: event.listener
        identifier: convertRelationFieldArraysToCsv
        event: FriendsOfTYPO3\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: setPid

  FriendsOfTYPO3\Interest\DataHandling\Operation\Event\Handler\SetPid:
    tags:
      - name: event.listener
        identifier: setPid
        event: FriendsOfTYPO3\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        after: convertRelationFieldArraysToCsv

  FriendsOfTYPO3\Interest\DataHandling\Operation\Event\Handler\RegisterValuesOfRelationFields:
    tags:
      - name: event.listener
        identifier: registerValuesOfRelationFields
        event: FriendsOfTYPO3\Interest\DataHandling\Operation\Event\RecordOperationInvocationEvent
        before: addResolvedPendingRelationsToDataHandler

  FriendsOfTYPO3\Interest\DataHandling\Operation\Event\Handler\AddResolvedPendingRelationsToDataHandler:
    tags:
      - name: event.listener
        identifier: addResolvedPendingRelationsToDataHandler
        event: FriendsOfTYPO3\Interest\DataHandling\Operation\Event\RecordOperationInvocationEvent
        before: processDatamap

  FriendsOfTYPO3\Interest\DataHandling\Operation\Event\Handler\ProcessDatamap:
    tags:
      - name: event.listener
        identifier: processDatamap
        event: FriendsOfTYPO3\Interest\DataHandling\Operation\Event\RecordOperationInvocationEvent
        before: processUpdatedForeignFieldValues

  FriendsOfTYPO3\Interest\DataHandling\Operation\Event\Handler\ProcessUpdatedForeignFieldValues:
    tags:
      - name: event.listener
        identifier: processUpdatedForeignFieldValues
        event: FriendsOfTYPO3\Interest\DataHandling\Operation\Event\RecordOperationInvocationEvent
        before: processCmdmap

  FriendsOfTYPO3\Interest\DataHandling\Operation\Event\Handler\ProcessCmdmap:
    tags:
      - name: event.listener
        identifier: processCmdmap
        event: FriendsOfTYPO3\Interest\DataHandling\Operation\Event\RecordOperationInvocationEvent
        before: setUid

  FriendsOfTYPO3\Interest\DataHandling\Operation\Event\Handler\SetUid:
    tags:
      - name: event.listener
        identifier: setUid
        event: FriendsOfTYPO3\Interest\DataHandling\Operation\Event\RecordOperationInvocationEvent
        before: mapNewUidToRemoteId

  FriendsOfTYPO3\Interest\DataHandling\Operation\Event\Handler\MapNewUidToRemoteId:
    tags:
      - name: event.listener
        identifier: mapNewUidToRemoteId
        event: FriendsOfTYPO3\Interest\DataHandling\Operation\Event\RecordOperationInvocationEvent
        before: persistPendingRelationInformation

  FriendsOfTYPO3\Interest\DataHandling\Operation\Event\Handler\PersistPendingRelationInformation:
    tags:
      - name: event.listener
        identifier: persistPendingRelationInformation
        event: FriendsOfTYPO3\Interest\DataHandling\Operation\Event\RecordOperationInvocationEvent
        before: processDeferredRecordOperations

  FriendsOfTYPO3\Interest\DataHandling\Operation\Event\Handler\ProcessDeferredRecordOperations:
    tags:
      - name: event.listener
        identifier: processDeferredRecordOperations
        event: FriendsOfTYPO3\Interest\DataHandling\Operation\Event\RecordOperationInvocationEvent
        before: updateCountOnForeignSideOfInlineRecord

  FriendsOfTYPO3\Interest\DataHandling\Operation\Event\Handler\UpdateCountOnForeignSideOfInlineRecord:
    tags:
      - name: event.listener
        identifier: updateCountOnForeignSideOfInlineRecord
        event: FriendsOfTYPO3\Interest\DataHandling\Operation\Event\RecordOperationInvocationEvent
        before: cleanUpPendingRelations

  FriendsOfTYPO3\Interest\DataHandling\Operation\Event\Handler\FixSortingPositionsOnRemoteRelationRecords:
    tags:
      - name: event.listener
        identifier: fixSortingPositionsOnRemoteRelationRecords
        event: FriendsOfTYPO3\Interest\DataHandling\Operation\Event\RecordOperationInvocationEvent
        before: cleanUpPendingRelations

  FriendsOfTYPO3\Interest\DataHandling\Operation\Event\Handler\RemovePendingRelationsForCreatedRecord:
    tags:
      - name: event.listener
        identifier: removePendingRelationsForCreatedRecord
        event: FriendsOfTYPO3\Interest\DataHandling\Operation\Event\RecordOperationInvocationEvent
        after: fixSortingPositionsOnRemoteRelationRecords

  FriendsOfTYPO3\Interest\DataHandling\Operation\Event\Handler\RemovePendingRelationsForDeletedRecord:
    tags:
      - name: event.listener
        identifier: removePendingRelationsForDeletedRecord
        event: FriendsOfTYPO3\Interest\DataHandling\Operation\Event\RecordOperationInvocationEvent
        after: foreignRelationSorting

  FriendsOfTYPO3\Interest\EventHandler\DeleteRemoteIdForDeletedFile:
    tags:
      - name: event.listener
        identifier: deleteRemoteIdForDeletedFile
        event: TYPO3\CMS\Core\Resource\Event\AfterFileDeletedEvent

  FriendsOfTYPO3\Interest\Command\CreateCommandController:
    tags:
      - name: console.command
        command: 'interest:create'
        schedulable: false

  FriendsOfTYPO3\Interest\Command\DeleteCommandController:
    tags:
      - name: console.command
        command: 'interest:delete'
        schedulable: false

  FriendsOfTYPO3\Interest\Command\UpdateCommandController:
    tags:
      - name: console.command
        command: 'interest:update'
        schedulable: false

  FriendsOfTYPO3\Interest\Command\ReadCommandController:
    tags:
      - name: console.command
        command: 'interest:read'
        schedulable: false

  FriendsOfTYPO3\Interest\Command\PendingRelationsCommandController:
    tags:
      - name: console.command
        command: 'interest:pendingrelations'
        schedulable: false

  FriendsOfTYPO3\Interest\Command\ClearRecordHashCommandController:
    tags:
      - name: console.command
        command: 'interest:clearhash'
        schedulable: false
