services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Pixelant\Interest\:
    resource: '../Classes/*'

  Pixelant\Interest\DataHandling\Operation\Event\Handler\InsertTranslationFieldsEventHandler:
    tags:
      - name: event.listener
        identifier: insertTranslationFields
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: resolveStoragePid

  Pixelant\Interest\DataHandling\Operation\Event\Handler\ResolveStoragePidEventHandler:
    tags:
      - name: event.listener
        identifier: resolveStoragePid
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: generateRecordOperationHash

  Pixelant\Interest\DataHandling\Operation\Event\Handler\GenerateRecordOperationHashEventHandler:
    tags:
      - name: event.listener
        identifier: generateRecordOperationHash
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: stopIfRepeatingPreviousRecord

  Pixelant\Interest\DataHandling\Operation\Event\Handler\StopIfRepeatingPreviousRecordOperation:
    tags:
      - name: event.listener
        identifier: stopIfRepeatingPreviousRecord
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: persistFileData

  Pixelant\Interest\DataHandling\Operation\Event\Handler\PersistFileDataEventHandler:
    tags:
      - name: event.listener
        identifier: persistFileData
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: deferSysFileReferenceRecordOperation

  Pixelant\Interest\DataHandling\Operation\Event\Handler\DeferSysFileReferenceEventHandler:
    tags:
      - name: event.listener
        identifier: deferSysFileReferenceRecordOperation
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: relationSortingAsMetaData

  Pixelant\Interest\DataHandling\Operation\Event\Handler\RelationSortingAsMetaDataEventHandler:
    tags:
      - name: event.listener
        identifier: relationSortingAsMetaData
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: validateFieldNamesEventHandler

  Pixelant\Interest\DataHandling\Operation\Event\Handler\ValidateFieldNamesEventHandler:
    tags:
      - name: event.listener
        identifier: validateFieldNamesEventHandler
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: setContentObjectRendererLanguage

  Pixelant\Interest\DataHandling\Operation\Event\Handler\SetContentObjectRendererLanguageEventHandler:
    tags:
      - name: event.listener
        identifier: setContentObjectRendererLanguage
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: applyFieldDataTransformations

  Pixelant\Interest\DataHandling\Operation\Event\Handler\ApplyFieldDataTransformationsEventHandler:
    tags:
      - name: event.listener
        identifier: applyFieldDataTransformations
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: sanitizeFieldValues

  Pixelant\Interest\DataHandling\Operation\Event\Handler\SanitizeFieldValuesEventHandler:
    tags:
      - name: event.listener
        identifier: sanitizeFieldValues
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: deferMissingPidRemoteId

  Pixelant\Interest\DataHandling\Operation\Event\Handler\DeferMissingPidRemoteIdEventHandler:
    tags:
      - name: event.listener
        identifier: deferMissingPidRemoteId
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: filterPendingRelations

  Pixelant\Interest\DataHandling\Operation\Event\Handler\FilterPendingRelationsEventHandler:
    tags:
      - name: event.listener
        identifier: filterPendingRelations
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: prepareRelations

  Pixelant\Interest\DataHandling\Operation\Event\Handler\PrepareRelationsEventHandler:
    tags:
      - name: event.listener
        identifier: prepareRelations
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: removeFieldsWithNullValue

  Pixelant\Interest\DataHandling\Operation\Event\Handler\RemoveFieldsWithNullValueEventHandler:
    tags:
      - name: event.listener
        identifier: removeFieldsWithNullValue
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        before: setPid

  Pixelant\Interest\DataHandling\Operation\Event\Handler\SetPidEventHandler:
    tags:
      - name: event.listener
        identifier: setPid
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationSetupEvent
        after: removeFieldsWithNullValue

  Pixelant\Interest\DataHandling\Operation\Event\Handler\DetectUpdatedForeignFieldValuesEventHandler:
    tags:
      - name: event.listener
        identifier: detectUpdatedForeignFieldValues
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationInvocationEvent
        before: convertArrayValuesToScalar

  Pixelant\Interest\DataHandling\Operation\Event\Handler\ConvertArrayValuesToScalarEventHandler:
    tags:
      - name: event.listener
        identifier: convertArrayValuesToScalar
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationInvocationEvent
        before: resolvePendingRelations

  Pixelant\Interest\DataHandling\Operation\Event\Handler\ResolvePendingRelationsEventHandler:
    tags:
      - name: event.listener
        identifier: resolvePendingRelations
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationInvocationEvent
        before: processDatamap

  Pixelant\Interest\DataHandling\Operation\Event\Handler\ProcessDatamapEventHandler:
    tags:
      - name: event.listener
        identifier: processDatamap
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationInvocationEvent
        before: processUpdatedForeignFieldValues

  Pixelant\Interest\DataHandling\Operation\Event\Handler\ProcessUpdatedForeignFieldValuesEventHandler:
    tags:
      - name: event.listener
        identifier: processUpdatedForeignFieldValues
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationInvocationEvent
        before: processCmdmap

  Pixelant\Interest\DataHandling\Operation\Event\Handler\ProcessCmdmapEventHandler:
    tags:
      - name: event.listener
        identifier: processCmdmap
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationInvocationEvent
        before: setUid

  Pixelant\Interest\DataHandling\Operation\Event\Handler\SetUidEventHandler:
    tags:
      - name: event.listener
        identifier: setUid
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationInvocationEvent
        before: mapRemoteId

  Pixelant\Interest\DataHandling\Operation\Event\Handler\MapRemoteIdEventHandler:
    tags:
      - name: event.listener
        identifier: mapRemoteId
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationInvocationEvent
        before: persistPendingRelationInformation

  Pixelant\Interest\DataHandling\Operation\Event\Handler\PersistPendingRelationInformationEventHandler:
    tags:
      - name: event.listener
        identifier: persistPendingRelationInformation
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationInvocationEvent
        before: processDeferredRecordOperations

  Pixelant\Interest\DataHandling\Operation\Event\Handler\ProcessDeferredRecordOperationsEventHandler:
    tags:
      - name: event.listener
        identifier: processDeferredRecordOperations
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationInvocationEvent
        before: updateCountOnForeignSideOfInlineRecord

  Pixelant\Interest\DataHandling\Operation\Event\Handler\UpdateCountOnForeignSideOfInlineRecordEventHandler:
    tags:
      - name: event.listener
        identifier: updateCountOnForeignSideOfInlineRecord
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationInvocationEvent
        before: cleanUpPendingRelations

  Pixelant\Interest\DataHandling\Operation\Event\Handler\ForeignRelationSortingEventHandler:
    tags:
      - name: event.listener
        identifier: foreignRelationSorting
        event: Pixelant\Interest\DataHandling\Operation\Event\RecordOperationInvocationEvent
        before: deleteRemoteIdForDeletedFile

  Pixelant\Interest\EventHandler\DeleteRemoteIdForDeletedFileEventHandler:
    tags:
      - name: event.listener
        identifier: deleteRemoteIdForDeletedFile
        event: TYPO3\CMS\Core\Resource\Event\AfterFileDeletedEvent

  Pixelant\Interest\Command\CreateCommandController:
    tags:
      - name: console.command
        command: 'interest:create'
        schedulable: false

  Pixelant\Interest\Command\DeleteCommandController:
    tags:
      - name: console.command
        command: 'interest:delete'
        schedulable: false

  Pixelant\Interest\Command\UpdateCommandController:
    tags:
      - name: console.command
        command: 'interest:update'
        schedulable: false

  Pixelant\Interest\Command\ReadCommandController:
    tags:
      - name: console.command
        command: 'interest:read'
        schedulable: false

  Pixelant\Interest\Command\PendingRelationsCommandController:
    tags:
      - name: console.command
        command: 'interest:pendingrelations'
        schedulable: false

  Pixelant\Interest\Command\ClearRecordHashCommandController:
    tags:
      - name: console.command
        command: 'interest:clearhash'
        schedulable: false
